kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "blog-django-py-pipeline"
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: https://raw.githubusercontent.com/alimuratunsal/blog-django-py/master/Jenkinsfile
    type: JenkinsPipeline
